dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
        maven {
            url 'https://jitpack.io'
            metadataSources {
                mavenPom()
                artifact()
            }
        }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/nexus/content/groups/public/' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/jcenter' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/google' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/gradle-plugin' }
    }
}

include ':xiguwen'
